// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vplcuepyzexsjaulmyan.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZwbGN1ZXB5emV4c2phdWxteWFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMjIwODYsImV4cCI6MjA2ODU5ODA4Nn0.wjbHImyVFkugRTYbsedYKClRcF4glqInaUaALoVgQRA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});